---
- hosts: webserver
  become: true
  tasks:
    - name: update repository index
      yum:
        update_cache: yes

    - name: install apache2 package
      yum:
        name: httpd

    - name: add php support for apache
      yum:
        name: php,php-common,php-cli,php-gd,php-curl,php-mysqlnd
