---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates [CentOS]
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates [Ubuntu/Debian]
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Ubuntu","Debian"]

- hosts: webserver
  become: true
  tasks:
    - name: install apache package with php [CentOS]
      yum:
        name:
          - httpd
          - php,php-cli
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Restart service httpd
      service:
        name: httpd
        state: started
      when: ansible_distribution == "CentOS"

    - name: install apache package with php [Ubuntu/Debian]
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu","Debian"]

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package [CentOS]
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package [Ubuntu/Debian]
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution in ["Ubuntu","Debian"]

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest
