---
- hosts: webserver
  become: true
  tasks:
    - name: update repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install apache2 package
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"

    - name: add php support for apache
      yum:
        name: php,php-common,php-cli,php-gd,php-curl,php-mysqlnd
      when: ansible_distribution == "CentOS"
    #Same thing but for Ubuntu and Debian servers
    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == ["Ubuntu", "Debian"]
