---
- name: Manage Users
  hosts: webserver
  become: true
  pre_tasks:
    - name: Read user configuration file
      set_fact:
        config_file_content: "{{ lookup('file', '/home/r4nw/project/ansible/user_info.txt') }}"

    - name: print debug
      debug:
        msg: "{{ item.split(',') }}"
      loop: "{{ config_file_content.split('\n') }}"
      
  tasks:
    - name: Create user groups
      group:
        name: "{{ item.split(',')[1] }}"
        state: present
      loop: "{{ config_file_content.split('\n') }}"
      when: item.split(',')[2] == 'true'
    
    - name: Create users
      user:
        name: "{{ item.split(',')[0] }}"
        groups: "{{ item.split(',')[1] }}"
        createhome: yes
        append: yes
      loop: "{{ config_file_content.split('\n') }}"
      when: item.split(',')[2] == 'true'
    
    - name: Add SSH public key for users
      authorized_key:
        user: "{{ item.split(',')[0] }}"
        state: present
        key: "{{ lookup('file', '/home/r4nw/.ssh/id_rsa.pub') }}"
      loop: "{{ config_file_content.split('\n') }}"
      when: item.split(',')[2] == 'true'
    
    - name: Update user openfile limits
      pam_limits:
        domain: "{{ item.split(',')[0] }}"
        limit_type: hard
        limit_item: nofile
        value: "{{ item.split(',')[3] }}"
      loop: "{{ config_file_content.split('\n') }}"
      when: item.split(',')[2] == 'true'

    - name: Update user process limits
      pam_limits:
        domain: "{{ item.split(',')[0] }}"
        limit_type: hard
        limit_item: nproc
        value: "{{ item.split(',')[4] }}"
      loop: "{{ config_file_content.split('\n') }}"
      when: item.split(',')[2] == 'true'