---
- name: Configure Users and SSH
  hosts: webserver
  become: true
  become_method: sudo
  become_user: root
  become_flags: "-H"
  vars:
    ansible_become_password: good
  tasks:
    - name: Ensure required user groups exist
      group:
        name: "{{ item.group }}"
        state: present
      loop: "{{ user_data }}"
      when: item.group is defined

    - name: Create users from user_data file
      user:
        name: "{{ item.username }}"
        password: "{{ '!' }}"
        state: present
        groups: "{{ item.group }}"
        createhome: yes
      loop: "{{ user_data }}"
      when: item.create_user | default(false) | bool

    - name: Enable key-based SSH access for users
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', ssh_public_key_path) }}"
        state: present
      loop: "{{ user_data }}"
      when: item.enable_ssh_key | default(false) | bool

    - name: Update user limits
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item.username }} hard nofile {{ item.file_limit }}"
      loop: "{{ user_data }}"
      when: item.file_limit is defined

      # You can add more tasks for other limit settings like process limits

  vars:
    user_data: "{{ lookup('file', 'user_info.txt').split('\n') }}"
    ssh_public_key_path: "/home/r4nw/.ssh/id_rsa.pub"
